In [1]:
import pandas as pd
df = pd.read_csv("employee_salary.csv")

In [2]:
df.head(2)

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271

In [6]:
df_selected = df[['EmployeeID','Name','Department']]
df_selected.head(2)

   EmployeeID        Name  Department
0           1  Employee_1   Marketing
1           2  Employee_2  Operations

In [8]:
df_selected = df.drop(columns = ['Department'])
df_selected.head(2)

,EmployeeID,Name,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,15,Master,53,Female,Delhi,111416
1,2,Employee_2,7,Bachelor,25,Female,Bangalore,95271

In [11]:
df_filtered = df[df['Age']>25]
df_filtered.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818

In [15]:
df_filtered = df[(df['Age'] > 35) & (df['Department'] == 'IT')]
df_filtered.head(1)

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064

In [19]:
df_filtered = df[df['Monthly_Salary'].notna()]
df_filtered.head(2)

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271

In [23]:
df_renamed = df.rename(columns = {
    'Experience_Years' : 'Experience',
    'Monthly_Salary':'Salary',
    'Education_Level':'Education'
})
df_renamed.head()

,EmployeeID,Name,Department,Experience,Education,Age,Gender,City,Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [25]:
df['Per_Month_Salary'] = df["Monthly_Salary"] / 12
df['Tax'] = df["Monthly_Salary"] * 0.2
df['Net_Salary'] = df["Monthly_Salary"] - df["Tax"]

In [26]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0

In [27]:
df.sort_values("Monthly_Salary")
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0

In [28]:
df.sort_values("Monthly_Salary", ascending=False)
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0

In [32]:
df.sort_values(["Department","Monthly_Salary"], ascending=[True,False]).head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179,9848.250000,23635.8,94543.2
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213,8434.416667,20242.6,80970.4
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404,6117.000000,14680.8,58723.2
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202,6016.833333,14440.4,57761.6
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484,5707.000000,13696.8,54787.2

In [33]:
print(df.isnull().sum())

EmployeeID          0
Name                0
Department          0
Experience_Years    0
Education_Level     0
Age                 0
Gender              0
City                0
Monthly_Salary      0
Per_Month_Salary    0
Tax                 0
Net_Salary          0
dtype: int64

In [42]:
df['Salary'] = df['Monthly_Salary'].fillna(df['Monthly_Salary'].mean())
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary,Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0,132450

In [48]:
df['Department'] = df['Department'].fillna('Unknown')
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary,Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0,132450

In [44]:
df_clean = df.dropna()
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary,Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0,132450

In [47]:
df_clean = df.dropna(subset=['Monthly_Salary'])
df_clean.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary,Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0,132450

In [35]:
df_unique = df.drop_duplicates()
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0

In [36]:
df.Name.value_counts()
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Per_Month_Salary,Tax,Net_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,9284.666667,22283.2,89132.8
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,7939.250000,19054.2,76216.8
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,5755.333333,13812.8,55251.2
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,7924.250000,19018.2,76072.8
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,11037.500000,26490.0,105960.0

In [37]:
df['EmployeeID'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [38]:
df_females = df[df['Gender'] == 'Female'][['Monthly_Salary','Age','Department']]
df_females.head()

   Monthly_Salary  Age  Department
0          111416   53   Marketing
1           95271   25  Operations
2           69064   51          IT
4          132450   36  Operations
7           44830   34          IT