In [21]:
import pandas as pd
df = pd.read_csv("employee_salary.csv")

#  Find all columns, data types, shape, first 10 rows

In [22]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [23]:
df_selected = df[['EmployeeID','Name','Department']]
df_selected.head()

   EmployeeID        Name  Department
0           1  Employee_1   Marketing
1           2  Employee_2  Operations
2           3  Employee_3          IT
3           4  Employee_4  Operations
4           5  Employee_5  Operations

In [24]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Experience_Years',
       'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary'],
      dtype='str')

In [25]:
df.dtypes

EmployeeID          int64
Name                  str
Department            str
Experience_Years    int64
Education_Level       str
Age                 int64
Gender                str
City                  str
Monthly_Salary      int64
dtype: object

In [26]:
df.shape

(50, 9)

In [27]:
df.head(10)

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893

In [28]:
#statistical summary

df.describe(include='all')

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
count,50.00000,50,50,50.000000,50,50.000000,50,50,50.0000
unique,NaN,50,5,NaN,4,NaN,2,5,NaN
top,NaN,Employee_1,Marketing,NaN,Master,NaN,Female,Delhi,NaN
freq,NaN,1,13,NaN,19,NaN,27,15,NaN
mean,25.50000,NaN,NaN,9.900000,NaN,39.760000,NaN,NaN,82288.8000
std,14.57738,NaN,NaN,5.349995,NaN,11.539745,NaN,NaN,33521.4379
min,1.00000,NaN,NaN,1.000000,NaN,22.000000,NaN,NaN,28420.0000
25%,13.25000,NaN,NaN,5.250000,NaN,28.250000,NaN,NaN,59424.0000
50%,25.50000,NaN,NaN,10.000000,NaN,43.500000,NaN,NaN,73890.5000
75%,37.75000,NaN,NaN,14.750000,NaN,49.000000,NaN,NaN,107219.0000
max,50.00000,NaN,NaN,19.000000,NaN,57.000000,NaN,NaN,149123.0000

In [29]:
df.describe()

       EmployeeID  Experience_Years        Age  Monthly_Salary
count    50.00000         50.000000  50.000000         50.0000
mean     25.50000          9.900000  39.760000      82288.8000
std      14.57738          5.349995  11.539745      33521.4379
min       1.00000          1.000000  22.000000      28420.0000
25%      13.25000          5.250000  28.250000      59424.0000
50%      25.50000         10.000000  43.500000      73890.5000
75%      37.75000         14.750000  49.000000     107219.0000
max      50.00000         19.000000  57.000000     149123.0000

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        50 non-null     int64
 1   Name              50 non-null     str
 2   Department        50 non-null     str
 3   Experience_Years  50 non-null     int64
 4   Education_Level   50 non-null     str
 5   Age               50 non-null     int64
 6   Gender            50 non-null     str
 7   City              50 non-null     str
 8   Monthly_Salary    50 non-null     int64
dtypes: int64(4), str(5)
memory usage: 3.6 KB

# Generate the complete statistical summary and answer the following. a)The maximum age b)The lowest salary c)The department with maximum employees

In [31]:
df_age = df['Age'].max()
print("The Maximum Age:",df_age)

The Maximum Age: 57

In [32]:
df_sal = df['Monthly_Salary'].min()
print("The Lowest Salary is:", df_sal)

The Lowest Salary is: 28420

In [33]:
df_max_emp = df.groupby("Department").count()
df1=df_max_emp['EmployeeID']
df1

Department
Finance       10
HR             7
IT            10
Marketing     13
Operations    10
Name: EmployeeID, dtype: int64

# Filter employees by age > 30

In [34]:
df_age = df[df['Age'] > 30]
df_age.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818

# Calculate annual salary

In [35]:
df['Annual_Salary'] = df['Monthly_Salary'] * 12
df[['Monthly_Salary','Annual_Salary']].head()

   Monthly_Salary  Annual_Salary
0          111416        1336992
1           95271        1143252
2           69064         828768
3           95091        1141092
4          132450        1589400

# Create a new data frame with only females, their salary, age and department

In [36]:
df_females = df[df['Gender'] == 'Female'][['Monthly_Salary','Age','Department']]
df_females.head()

   Monthly_Salary  Age  Department
0          111416   53   Marketing
1           95271   25  Operations
2           69064   51          IT
4          132450   36  Operations
7           44830   34          IT

# Find the unique values of column education level

In [37]:
df['Education_Level'].unique()

<StringArray>
['Master', 'Bachelor', 'High School', 'PhD']
Length: 4, dtype: str

# Find the count of people belonging to each city

In [38]:
df.City.value_counts()

City
Delhi        15
Hyderabad    12
Bangalore    11
Mumbai        7
Chennai       5
Name: count, dtype: int64

# Filter the male employees with salary more than 50000

In [39]:
df[(df['Gender']== 'Male') & (df['Monthly_Salary'] > 50000)]
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Annual_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,1336992
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,1143252
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,828768
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,1141092
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,1589400

# Lab Session DAY 2

In [43]:
df_males = df[df['Gender'] == 'Male'][['Gender', 'Monthly_Salary', 'Age']] \
    .sort_values(
        by=['Monthly_Salary', 'Age'],
        ascending=[True, False]
    )
df_males.head()

   Gender  Monthly_Salary  Age
13   Male           28436   27
25   Male           30600   24
9    Male           31893   28
8    Male           42429   53
38   Male           43589   24

In [48]:
df_female = df[df['Gender'] == 'Female'][['Gender', 'Monthly_Salary', 'Age']] \
    .sort_values(
        by=['Monthly_Salary', 'Age'],
        ascending=[True, False]
    )

df_female.head()

    Gender  Monthly_Salary  Age
48  Female           28420   23
16  Female           30895   41
17  Female           44738   51
7   Female           44830   34
46  Female           58828   22

In [57]:
df_salary = pd.DataFrame({
    'EmployeeID': df['EmployeeID'],
    'Gross_Salary': df['Monthly_Salary'] * 12,
    'Tax_Paid': (df['Monthly_Salary'] * 12) * 0.20,
    'Net_Salary': (df['Monthly_Salary'] * 12) - ((df['Monthly_Salary'] * 12) * 0.20),
    'Next_Year_Salary': ((df['Monthly_Salary'] * 12) - ((df['Monthly_Salary'] * 12) * 0.20)) * 0.30
})

df_salary.head()

   EmployeeID  Gross_Salary  Tax_Paid  Net_Salary  Next_Year_Salary
0           1       1336992  267398.4   1069593.6         320878.08
1           2       1143252  228650.4    914601.6         274380.48
2           3        828768  165753.6    663014.4         198904.32
3           4       1141092  228218.4    912873.6         273862.08
4           5       1589400  317880.0   1271520.0         381456.00

In [71]:
df_dept = df.groupby(['Department', 'Gender'])['Monthly_Salary'] \
            .sum() \
            .reset_index() \
            .sort_values(by=['Monthly_Salary'], ascending=True)

df_dept.head()

   Department  Gender  Monthly_Salary
1     Finance    Male          224091
3          HR    Male          225337
9  Operations    Male          319818
2          HR  Female          355279
5          IT    Male          356028

In [67]:
df_edu = df.groupby('Education_Level')[['Age', 'Monthly_Salary']] \
            .sum() \
            .reset_index() \
            .sort_values(by=['Age', 'Monthly_Salary'], ascending=[True, False])

df_edu

  Education_Level  Age  Monthly_Salary
0        Bachelor  349          741976
3             PhD  410          729441
1     High School  481         1004117
2          Master  748         1638906