# Ques4:Load the iris dataset and find a)What is the probability that a flower is Setosa given that petal length is greater than 1.4cm(0.89)b)A flower is chosen with Sepal length is greater than 6cm. What is the probability that chosen floweris Versicolor.(0.27)

In [1]:
import seaborn as sns

In [2]:
df1 = sns.load_dataset('iris')

In [3]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
p_setosa = len(df1[df1['species'] == 'setosa'])/len(df1)
p_petal_given_setosa = len(
    df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)]
) / len(
    df1[df1['species'] == 'setosa']
)
p_petal = len(df1[df1['petal_length'] > 1.4])/len(df1)

prob_a = (p_petal_given_setosa*p_setosa)/p_petal
print(f"Setosa | Petal Length > 1.4: {round(prob_a, 2)}")

Setosa | Petal Length > 1.4: 0.21

In [5]:
 df1[(df1['species'] == 'setosa')]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [6]:
df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)]

    sepal_length  sepal_width  petal_length  petal_width species
3            4.6          3.1           1.5          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
7            5.0          3.4           1.5          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
34           4.9          3.1           1.5          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
46           5.1          3.8           1.6          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa

In [7]:
p_setosa = len(df1[df1['species'] == 'setosa'])/len(df1) p_petal_given_setosa = len( df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)] ) / len( df1[df1['species'] == 'setosa'] ) p_petal = len(df1[df1['petal_length'] > 1.4])/len(df1) prob_a = (p_petal_given_setosa*p_setosa)/p_petal print(f"Setosa | Petal Length > 1.4: {round(prob_a, 2)}")

SyntaxError: invalid syntax (1133688615.py, line 1)

In [ ]:
p_setosa = len(df1[df1['species'] == 'setosa']) / len(df1)
p_petal_given_setosa = len(
    df1[
        (df1['species'] == 'setosa') &
        (df1['petal_length'] > 1.4)
    ]
) / len(df1[df1['species'] == 'setosa'])
p_petal = len(
    df1[df1['petal_length'] > 1.4]
) / len(df1)
prob_a = (p_petal_given_setosa * p_setosa) / p_petal

print(f"P(Setosa | Petal Length > 1.4) = {round(prob_a, 2)}")

In [ ]:
df1.head()

In [ ]:
p_versicolor = len(df1[df1['species'] == 'versicolor']) / len(df1)

p_sepal_given_versicolor = len(
    df1[
        (df1['species'] == 'versicolor') &
        (df1['sepal_length'] > 6)
    ]
) / len(df1[df1['species'] == 'versicolor'])

p_sepal = len(
    df1[df1['sepal_length'] > 6]
) / len(df1)

prob_b = (p_sepal_given_versicolor * p_versicolor) / p_sepal

prob_b