# Assignment 2

A factory has two machines. Machine A produces 70%of the items and has a 4% defect rate. Machine B produces 30%of the items and has a 5% defect rate. If a randomly selected item is found to be defective, what is the probability that it was produced by Machine A?(0.6512

In [1]:

P_A = 0.7      
P_B = 0.3      

P_D_given_A = 0.04   
P_D_given_B = 0.05   


P_D = (P_A * P_D_given_A) + (P_B * P_D_given_B)


P_A_given_D = (P_D_given_A * P_A) / P_D


print("Probability that defective item was produced by Machine A:")
print(round(P_A_given_D, 4))

Probability that defective item was produced by Machine A:
0.6512

A disease affects 2% of the population. A medical test detects disease correctly by 95% and false positive rate is 10%. Find the probability that a person actually has disease if test result is positive

In [2]:
p_d = 0.02                 
p_not_d = 0.98             

p_t_given_d = 0.95            
p_t_given_not_d = 0.10     


p_t = (p_d * p_t_given_d) + (p_not_d * p_t_given_not_d)


p_d_given_t = (p_t_given_d * p_d) / p_t


print(f"Probability that person is actually diseased: {p_d_given_t:.4f}")

Probability that person is actually diseased: 0.1624

A company has three suppliers. Supplier A supplies 50%of the parts, with 2% defective. Supplier B supplies 30%of the parts, with 3% defective. Supplier C supplies 20%of the parts, with 5% defective. From the total production, a part is selected at random and is found to be defective.What is the probability that the defective part came from Supplier C

In [3]:
p_a = 0.5
p_b = 0.3
p_c = 0.2
p_d_given_a = 0.02
p_d_given_b = 0.03
p_d_given_c = 0.05
p_d = (p_a*p_d_given_a)+(p_b*p_d_given_b)+(p_c*p_d_given_c)
p_c_given_d =(p_c*p_d_given_c)/p_d
p_c_given_d
print("p_c_given_d =", round(p_c_given_d, 3))

p_c_given_d = 0.345

# Assignment 4

# Ques4:Load the iris dataset and find a)What is the probability that a flower is Setosa given that petal length is greater than 1.4cm(0.89)b)A flower is chosen with Sepal length is greater than 6cm. What is the probability that chosen floweris Versicolor.(0.27)

In [4]:
import seaborn as sns

In [5]:
df1 = sns.load_dataset('iris')

In [8]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [31]:
p_setosa = len(df1[df1['species'] == 'setosa'])/len(df1)
p_petal_given_setosa = len(
    df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)]
) / len(
    df1[df1['species'] == 'setosa']
)
p_petal = len(df1[df1['petal_length'] > 1.4])/len(df1)

prob_a = (p_petal_given_setosa*p_setosa)/p_petal
print(f"Setosa | Petal Length > 1.4: {round(prob_a, 2)}")

Setosa | Petal Length > 1.4: 0.52

In [24]:
 df1[(df1['species'] == 'setosa')]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [28]:
df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)]

    sepal_length  sepal_width  petal_length  petal_width species
3            4.6          3.1           1.5          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
7            5.0          3.4           1.5          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
34           4.9          3.1           1.5          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
46           5.1          3.8           1.6          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa

In [32]:
p_setosa = len(df1[df1['species'] == 'setosa'])/len(df1) p_petal_given_setosa = len( df1[(df1['species'] == 'setosa') & (df1['petal_length'] > 1.4)] ) / len( df1[df1['species'] == 'setosa'] ) p_petal = len(df1[df1['petal_length'] > 1.4])/len(df1) prob_a = (p_petal_given_setosa*p_setosa)/p_petal print(f"Setosa | Petal Length > 1.4: {round(prob_a, 2)}")

SyntaxError: invalid syntax (1133688615.py, line 1)

In [33]:
p_setosa = len(df1[df1['species'] == 'setosa']) / len(df1)
p_petal_given_setosa = len(
    df1[
        (df1['species'] == 'setosa') &
        (df1['petal_length'] > 1.4)
    ]
) / len(df1[df1['species'] == 'setosa'])
p_petal = len(
    df1[df1['petal_length'] > 1.4]
) / len(df1)
prob_a = (p_petal_given_setosa * p_setosa) / p_petal

print(f"P(Setosa | Petal Length > 1.4) = {round(prob_a, 2)}")

P(Setosa | Petal Length > 1.4) = 0.21

In [37]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
p_versicolor = len(df1[df1['species'] == 'versicolor']) / len(df1)

p_sepal_given_versicolor = len(
    df1[
        (df1['species'] == 'versicolor') &
        (df1['sepal_length'] > 6)
    ]
) / len(df1[df1['species'] == 'versicolor'])

p_sepal = len(
    df1[df1['sepal_length'] > 6]
) / len(df1)

prob_b = (p_sepal_given_versicolor * p_versicolor) / p_sepal

prob_b

0.32786885245901637